name: EarthCommands
version: '${project.version}'
main: me.oliver193.earthCommands.EarthCommands
api-version: '1.19'
authors: [ oliver193 ]
description: Basic commands for the Earth Server.
website: https://0000024.xyz/earth.php
commands:
  serverinfo:
    permission: earthcommands.serverinfo
    description: View basic info about the server.
    usage: /<command>
  map:
    permission: earthcommands.map
    description: Provides a link to the map of the server.
    usage: /<command>
  about:
    permission: earthcommands.about
    description: Provides information about the server.
    usage: /<command>